قراءة البيانات

In [ ]:
import pandas as pd

df = pd.read_csv('retail_store_sales.csv')

df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

معلمومات عن البيانات

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11539 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11229 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12375 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

حجم البيانات

In [47]:
df.shape

(12575, 11)

معرفة القيم الناقصة

In [48]:
df.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit      1036
Quantity             604
Total Spent         1346
Payment Method         0
Location             200
Transaction Date       0
Discount Applied    4199
dtype: int64

التأكد من الصفوف المكررة

In [49]:
df.duplicated().sum()

np.int64(0)

ملخص عام عن البيانات

In [50]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11539.000000  11971.000000  11229.000000
mean        23.376332      5.536380    129.522397
std         10.735116      2.857883     94.522331
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     52.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

حذف الصفوف المكررة إذا كانت موجودة

In [51]:
df1 = df.drop_duplicates()

التعامل مع القيم الفارغة

حذف القيم الفارغة التي في عمود ال item كونها لا يمكن تعبئتها

In [52]:
df1.dropna(subset=["Item"], inplace = True)

In [53]:
df1.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit       406
Quantity               0
Total Spent          709
Payment Method         0
Location             181
Transaction Date       0
Discount Applied    3783
dtype: int64

تعبئة القيم الفارغة في عمود سعر الواحدة بالمتوسط

In [54]:
df1["Price Per Unit"] = df1["Price Per Unit"].fillna(df1["Price Per Unit"].mean())

In [55]:
df1.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent          709
Payment Method         0
Location             181
Transaction Date       0
Discount Applied    3783
dtype: int64

تعبئة القيم الفارغة في عمود الإجمالي بقيمة الضرب بين عمود الكمية وعمود سعر الواحدة

In [56]:
df1["Total Spent"] = df1["Price Per Unit"] * df1["Quantity"]

In [57]:
df1.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location             181
Transaction Date       0
Discount Applied    3783
dtype: int64

تعبئة القيم الفارغة في عمود المنطقة بقيمة unknown

In [58]:
df1["Location"].fillna("Unknown", inplace = True)

C:\Users\abdos\AppData\Local\Temp\ipykernel_16732\2568115280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Location"].fillna("Unknown", inplace = True)

In [59]:
df1.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    3783
dtype: int64

تعبئة القيم الفارغة في عمود الخصم بقيمة false

In [60]:
df1["Discount Applied"].fillna("False", inplace = True)

C:\Users\abdos\AppData\Local\Temp\ipykernel_16732\1747273885.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Discount Applied"].fillna("False", inplace = True)

In [61]:
df1.isna().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

نتأكد من القيم داخل كل عمود

In [62]:
df1['Category'].value_counts()

Category
Furniture                             1460
Electric household essentials         1437
Beverages                             1427
Food                                  1426
Milk Products                         1425
Butchers                              1421
Computers and electric accessories    1397
Patisserie                            1369
Name: count, dtype: int64

In [63]:
df1['Payment Method'].value_counts()

Payment Method
Cash              3917
Credit Card       3729
Digital Wallet    3716
Name: count, dtype: int64

In [64]:
df1['Location'].value_counts()

Location
Online      5645
In-store    5536
Unknown      181
Name: count, dtype: int64

تحويل نوع بيانات التاريخ

In [66]:
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"])

حفظ البيانات النظيفة

In [67]:
df.to_csv("retail_store_sales_cleaned.csv", index=False)